apiVersion: v1
kind: Service
metadata:
  name: jlc-bookstore-service
  labels:
    app: jlc-bookstore-service
    tier: front-end    
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jlc-bookstore
    tier: front-end
